### ISSUE TITLE
React front end for Gift Aid form

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#1]
As part of the move to serverless Gift Aid form, we need to build the front end in React. Will need additional tickets to break this down.

Essential Requirements:
- [x] User checks a box to say yes to Giftaid
- [x] User enters a valid UK mobile number (starting 07 or +44 and then 9 additional numbers)
- [x] User enters First name
- [x] User enters Last name
- [x] User enters postcode
- [x] User searched for address based on submitted postcode 
- [x] User selects address an address from a list of addresses
- [x] OR if cannot find address, user enters an address manually
- [x] User submits the data 
- [x] User receives confirmation of successful submission
- [x] Data is sent to the Comic Relief database 

![image](https://user-images.githubusercontent.com/23260070/38424802-1580881e-39aa-11e8-8052-4d54d7a2ae48.png)

![image](https://user-images.githubusercontent.com/23260070/38425496-eb86b1e4-39ab-11e8-8617-c1af5340ccbf.png)

**Comment by LaBustaffa** [comment]
The journey has been tested. See this test on the WhatUsersDo platform: https://app.whatusersdo.com/app/client/tests/42811/videos
