### ISSUE TITLE
Confirmation email

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#10]
Investigate 
As we don't collect email addresses in the form, could we send a receipt via SMS to confirm their giftaid declaration? 
Test with users - how surpised/delighted are they? Is it worth the cost?

subtask of #1

**Comment by LaBustaffa** [comment]
Is SMS the right way? Or are they willing to give us email? 
They cost 2.5 pence per message.

**Comment by CarolineRennie** [comment]
Closing as we don't send confirmation email
