### ISSUE TITLE
Add marketing consent to Gift Aid

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/giftaid-react#107]
Hear more about the project Comic Relief funds and other ways you can support our work including fundraising, campaigns and products.

How would you like to hear from us?

Email    y[ ]   n[ ]
_If yes then open email address field (as with the marketing preferences form)_
Post      y[ ]   n[ ]

Phone  y[ ]   n[ ]

SMS      y[ ]   n[ ]

You can update your communication preferences at any time at comicrelief.com/update-your-preferences. Your details will be kept safe, check out our privacy policy [https://www.comicrelief.com/privacy-notice] for more details.

**Comment by Heleen-cr** [comment]
@CarolineRennie btw in the text underneath the checkboxes should "comicrelief.com/update-your-preferences" be a link or should it just be exactly like that so people don't go there :p

**Comment by Heleen-cr** [comment]
@KrupaPammi could you test this on staging when you get the chance?
https://giftaid-staging.comicrelief.com/

(pipeline is currently paused for production)

**Comment by KrupaPammi** [comment]
@Heleen-cr Verified this, below are few issues found

1. Update-your-preferences link red underline is too long on mobile devices.
2. Clicking on comicrelief.com/update-your-preferences is giving a 404 error https://www.comicrelief.com/update-your-preferences.?_ga=2.258078089.283554500.1551087689-1273443089.1551087689
3. Timestamp on markerting prefs messages should be in unix format. Have raised a ticket for this on MP repo https://github.com/comicrelief/serverless-marketing-preferences/issues/12

**Comment by CarolineRennie** [comment]
Full stop shouldn't be in the URL for the preferences

**Comment by KrupaPammi** [comment]
@CarolineRennie I guess we should update the JIT copy to add email as well now that the field has been added in the marketing consent?

**Comment by Heleen-cr** [comment]
oops yeah I accidentally copied the full stop in the link's href.

**Comment by Heleen-cr** [comment]
@KrupaPammi fixed the link there. Should be on staging soon.

**Comment by KrupaPammi** [comment]
Thanks @Heleen-cr, will pick it up as priority first thing tomorrow, i'm leaving home now. We also need @s-barrah to fix the timestamp issue on marketing prefs mesages.

**Comment by KrupaPammi** [comment]
Have verified the link and timestamp fix, both look expected now. Sorry I found another issue of optional fields address 2 and address 3 in marketing prefs messages in SQS are saving empty string when there's no data entered. Should be default to null. @s-barrah is looking into it.

**Comment by KrupaPammi** [comment]
Thanks @s-barrah for the quick fix to set the optional field values to null when no data entered. Working as expected now.
