### ISSUE TITLE
Update Just In Time notification

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/giftaid-react#108]
Copy is not correct on Gift Aid JIT- please change to be:

**Name**, **phone number** **and address**: we need these details to process a Gift Aid claim on your donation.

**Comment by s-barrah** [comment]
> Copy is not correct on Gift Aid JIT- please change to be:
> 
> **Name**, **phone number** **and address**: we need these details to process a Gift Aid claim on your donation.

Should this be updated for both submissions and update?
