### ISSUE TITLE
Sorry page

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#11]
We probably need to add a sorry page too.
Add as route + add some backend logic

subtask of #1

**Comment by LaBustaffa** [comment]
Design completed. 

![image](https://user-images.githubusercontent.com/33353053/41548737-b48672de-731b-11e8-8368-5a31629241da.png)

Can also be found here: https://comicrelief.box.com/s/ohurat3a60js6ekj5lcqq01ar3qbluii

**Comment by deniselashlley** [comment]
@adamclark-dev need to do backend stuff
@pradip3271  ready for testing https://deploy-preview-39--giftaid-react.netlify.com/

**Comment by pradip3271** [comment]
Passed QA, ready for release.

**Comment by Heleen-cr** [comment]
Backend bit needs to be done..

**Comment by Heleen-cr** [comment]
done now
