### ISSUE TITLE
Make optional fields values to be `Null` when there's no data provided 

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#114]
giftaid update

- Email

In giftaid and giftaid update

- Address 2

- Address 3

Ref: https://github.com/comicrelief/data-contracts/blob/master/contracts/giftaid-update.yml

**Comment by s-barrah** [comment]
@KrupaPammi pls note that nullable does not mean the value should be equal to null, it means it can be empty. Please speak to Corin about this.

**Comment by KrupaPammi** [comment]
@s-barrah I've checked with @corinja about this, when no data provided, values should be `Null`

**Comment by KrupaPammi** [comment]
Verified on production, fields that do not have values save as `null` now on main giftaid and giftaid update forms.
