### ISSUE TITLE
Adding a string instead of real UUID's in giftaid-update url is going to a sorry page

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#115]
Eg: https://giftaid-staging.comicrelief.com/update/test is going to a sorry page.

it accepts only real UUID's

https://dashboard.iopipe.com/project/65d0875a-e96a-4a1e-8a08-976790bf45d2/alert/1001a1af-ae07-445f-af4d-139d2db0f7d8/event/8644a375-dd0c-4541-8baf-18db465632ef

**Comment by KrupaPammi** [comment]
@s-barrah it shouldn't I guess, hence we see this issue.

**Comment by KrupaPammi** [comment]
@s-barrah Verified, works as expected.

**Comment by KrupaPammi** [comment]
@Sidney Barrah have re-opened this issue again to pick it up sometime next week, we need to update the UUID pattern to accept transaction id in small letters. Currently seeing an error message when I  add a transaction id in small letters as it is allowing only capitals in the pattern.
eg: PSL ID: `bb9aa5c9-5d93-4a34-a102-aaf378d16a73`

Gaps ID pattern will remain the same

**Comment by KrupaPammi** [comment]
@AndyEPhipps @Heleen-cr Could anyone of you both can look into this issue sometime next week to update the pattern regex to match the PSL id by removing the capital letters and mking it allow small letters for this url https://giftaid.comicrelief.com/update/7aaaff46-311c-11e9-8904-0ea501966b62, the form is giving an error surrenctly if we add this type of PSL id.

**Comment by Heleen-cr** [comment]
I was going to say sure... but eh @s-barrah it looks like you're fixing it meanwhile?

**Comment by KrupaPammi** [comment]
thanks @s-barrah and @Heleen-cr

**Comment by KrupaPammi** [comment]
After discussion with Adam and Peter, we need to remove the validation on transaction id field and in the url keeping minimum validation that the field should not be null.
