### ISSUE TITLE
Storybook version for Postcode Lookup error handling

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#121]

**Comment by Heleen-cr** [comment]
### Test notes:

- go to: https://deploy-preview-122--giftaid-react.netlify.com/
- Fill in the form and submit. It should go to the success page. If a field has an error it should not allow you to submit.
- Open the console and block the postcode lookup url in the network tab.
- When you click the "find address" button there should be a message telling the user to add their address manually.
- You should be able to submit the form and if there are any errors you shouldn't be allowed to submit the form.

**Comment by KrupaPammi** [comment]
Verified, works as expected.
