### ISSUE TITLE
Links on giftaid/giftaid-update thank you pages are pointing to Sport relief/where-your-money-goes instead of CR

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#128]

**Comment by s-barrah** [comment]
@KrupaPammi can you please provide the correct links? Thanks.

**Comment by s-barrah** [comment]
![screen shot 2019-02-07 at 09 55 30](https://user-images.githubusercontent.com/27994450/52403460-ad3b2c80-2abe-11e9-8368-9d6b037884cd.png)

**Comment by KrupaPammi** [comment]
@CarolineRennie @Heleen-cr Do we need to remove the row with the links that point to SR, like we are doing on donate?

**Comment by Heleen-cr** [comment]
yes probably

**Comment by Heleen-cr** [comment]
sorry what I mean is the whole card row as without the links it doesn't make sense. 
So from (and including) the text saying "These are some of the people we helped last year:"
and then the rest of the images and links on the card row.

Leave the "Read more" button I'd say.

**Comment by KrupaPammi** [comment]
Verified, looks as expected
