### ISSUE TITLE
On Prod: Submitting on main giftaid form is creating 3 same entries with minor milliseconds difference for each entry in data team DB.

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#132]

**Comment by corinja** [comment]
I have switched off the production Gift Aid consumer until this is resolved, as it is creating 'duplicate' entries in our GA table in EpWebServices database. Once the issue is resolved I will switch the queue consumer back on.

**Comment by adamclark-dev** [comment]
Just had a look at this, looks like it's the frontend causing this issue.

**Comment by KrupaPammi** [comment]
Verified on staging and production for both giftaid main and update form, messages in the SQS queue consuming only once per submission and saving in the DB as expected.
