### ISSUE TITLE
Postcode length validation failing

### ISSUE THREAD

**Issue by corinja** [comicrelief/giftaid-react#149]
The maximum length for the postcode field should be 20 characters as per https://cr-data-contracts.apps.comicrelief.com/giftaid

Data is being submitted where LEN(Postcode) > 20. Please investigate and fix.

**Comment by corinja** [comment]
Revision: postcode field needs to be 15 chars. Have updated data contract for giftaid.

**Comment by KrupaPammi** [comment]
Verfied on giftaid staging, works as expected

**Comment by corinja** [comment]
The most recent transaction I see with data > 15 chars in postcode field is 2019-03-03 22:33. Has the fix now been deployed in production?
