### ISSUE TITLE
Save mobile number value for phone when phone is 1 in marketing consent on giftaid

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#151]
Current behaviour: when I opted `yes` for phone, value for phone field in the DB is saving as `null`. Have discussed with @corinja. We should save the mobile field value for phone when phone is 1 https://cr-data-contracts.apps.comicrelief.com/marketing-preferences-sqs

**Comment by KrupaPammi** [comment]
@s-barrah I've tested this, phone is still saving as `null` when yes is said to Phone checkbox

**Comment by s-barrah** [comment]
I have tested this and the phone number field is not empty

**Comment by KrupaPammi** [comment]
Forgot to close this issue. This works fine now, saving the expected data.
