### ISSUE TITLE
Cookie message

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#16]
subtask of #1 
<img width="400" alt="screen shot 2018-04-18 at 16 34 21" src="https://user-images.githubusercontent.com/21171954/38942352-766a6a3e-4326-11e8-9e41-db2a8a130266.png">
<img width="1196" alt="screen shot 2018-04-18 at 16 34 44" src="https://user-images.githubusercontent.com/21171954/38942356-77ee1040-4326-11e8-8602-a34e8477872e.png">

**Comment by CarolineRennie** [comment]
Create in storybook too please

**Comment by deniselashlley** [comment]
ready for QA https://deploy-preview-34--giftaid-react.netlify.com/

**Comment by pradip3271** [comment]
Passed QA, ready for release.
