### ISSUE TITLE
Email required for 'No' to email

### ISSUE THREAD

**Issue by corinja** [comicrelief/giftaid-react#169]
This relates to https://github.com/comicrelief/giftaid-react/issues/107

If the user clicks No to email they are not required to submit an email address. However, it is not possible to match this incoming GiftAid record to existing supporter records that have an email address. 

Request that clicking either 'No' or 'Yes' exposes the email address input box and makes a valid email address value in this field a mandatory requirement to submit the form.

**Comment by CarolineRennie** [comment]
If we have an email for the supporter, we should be able to match on other data via Trillium in order to unsubscribe them - otherwise we are collecting data we don't need if we collect emails on every person who says no.

**Comment by corinja** [comment]
Closing as decision to create integration via another means, matching incoming mobile number to existing supporter and unsubscribing any associated email addresses that are already subscribed.
