### ISSUE TITLE
Pre-populate mobile number when redirected from SMS

### ISSUE THREAD

**Issue by s-barrah** [comicrelief/giftaid-react#179]
Pre-populate mobile number when redirected from SMS
https://github.com/comicrelief/react-donation/issues/621

**Comment by AndyEPhipps** [comment]
From prev ticket:

Found this old jira link related to this and adding it here for our reference https://comicrelief.atlassian.net/browse/SMSGA-11

 @ajgowans
 Author
ajgowans(Andrew Gowans) commented on May 29
Once this is implemented, could it also be used to autofill the Phone and SMS inputs on the permissions page?
https://www.comicrelief.com/update

**Comment by KrupaPammi** [comment]
> From prev ticket:
> 
> Found this old jira link related to this and adding it here for our reference https://comicrelief.atlassian.net/browse/SMSGA-11
> 
> @ajgowans
> Author
> ajgowans(Andrew Gowans) commented on May 29
> Once this is implemented, could it also be used to autofill the Phone and SMS inputs on the permissions page?
> https://www.comicrelief.com/update

@ajgowans we have permissions on https://giftaid-staging.comicrelief.com/uX8R5SzcKfk= already why do we want to duplicate it on https://www.comicrelief.com/update? I would say this may confuse the user.
