### ISSUE TITLE
Validation not working if phone number not entered

### ISSUE THREAD

**Issue by pvhee** [comicrelief/giftaid-react#188]
Phone number validation (or any validation) only works if a value is first entered then removed.

We need to make sure validation works even if no values are submitted.

This resulted in 100s of submissions triggering back-end validation errors. 100s of users would have gotten a sorry page (instead of a validation warning) and we've got many errors triggered via iopipe slack alerts.

**Comment by pvhee** [comment]
@s-barrah @Heleen-cr any idea why validation was working this way?

\cc @gusliedke

**Comment by Heleen-cr** [comment]
think it's a react rendering thing we might not have implemented properly? Dunno. Need to dive into it to see what's happening.

**Comment by AndyEPhipps** [comment]
On https://giftaid.comicrelief.com/ _I'm_ able to submit an incomplete form and it shows the errors in the FE okay?

![Screen Shot 2019-07-22 at 14 50 06](https://user-images.githubusercontent.com/4737220/61637812-1939d780-ac90-11e9-90c8-e9a90df07c79.png)

**Comment by AndyEPhipps** [comment]
So year, like if you check the first GA checkbox, fill in the other fields and submit, it **WILL** submit (to BE error) and forward to Sorry. Need to suss out what the Validation object is doing; the phone field is already required and _does_ error if you also don't fill in other fields... 🤔
