### ISSUE TITLE
Can't submit giftaid update form when no is selected and email in email(optional) field is not entered

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#190]
On https://giftaid-staging.comicrelief.com/update when input in all the fields are entered except for email(optional) field and then click on 'no' radio button for giftaid declaration, notice form is not getting submitted. 

Email field is optional but form is still making it as a required input before submitting it

**Comment by AndyEPhipps** [comment]
QA-able here: https://deploy-preview-191--giftaid-react.netlify.com/

**Comment by KrupaPammi** [comment]
@AndyEPhipps I tested this, FE side works as expected and i'm able to submit the form with or without an email input. However, I need to test the BE data for which we don't have a sandbox queue  setup on giftaid update, we just have staging queue, so I suggest we merge this keeping the prod deploy paused. I'll test it on staging and once all good we can unpause it.

**Comment by AndyEPhipps** [comment]
Thanks @KrupaPammi , can do
