### ISSUE TITLE
Tracking Update Requirement Giftaid for Emarsys 

### ISSUE THREAD

**Issue by phiral** [comicrelief/giftaid-react#199]
Can we please implement the dataLayer in the file below:

The main requirement for this capturing the email address in the 'userEmail' field when it is made available. This will then need to be propagated on each page or URL type.

See following for instructions:
[GiftAid_Global-Tracking-Instructions_20190716.txt](https://github.com/comicrelief/giftaid-react/files/3574395/GiftAid_Global-Tracking-Instructions_20190716.txt)

For information on why this is required please review the following Emarsys documentation:
https://help.emarsys.com/hc/en-us/articles/360005884453-identifying-users-with-web-extend

**Comment by Heleen-cr** [comment]
I've been able to add stuff to the datalayer, but it won't update once the email is filled in.

**Comment by Heleen-cr** [comment]
fixed and live.
