### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#2]
subtask of #1 

Header containing comic relief logo and campaign logo(s)

**Comment by Heleen-cr** [comment]
@CarolineRennie 
Do we want the campaign logo to change according to the campaign? At the moment we're showing both the RND and SR logos.

**Comment by CarolineRennie** [comment]
We want the one which shows both as this way the declaration counts across all Giftaid-able SMS donations during that 12 month period

**Comment by Heleen-cr** [comment]
### Test notes
https://deploy-preview-13--giftaid-react.netlify.com/

- the CR logo should be left aligned and should link to the CR website
- on our smallest (mobile) breakpoints the campaign logos should be right aligned
- from our medium( 740px) breakpoint on the campaign logos should be left aligned next to the CR logo.
- The header should be accessible

**Comment by pradip3271** [comment]
Passed QA, ready for release.
