### ISSUE TITLE
Gift Aid Form Copy Change (taking past 4 years and all future)

### ISSUE THREAD

**Issue by ajgowans** [comicrelief/giftaid-react#204]
Currently on the 2 GA forms here:
https://donation.comicrelief.com/form/giftaid
https://giftaid.sportrelief.com/update

it states:
‘Yes, I would like Comic Relief to claim Gift Aid on my donation *’

It needs to be updated to:

 'Yes, I would like Comic Relief to claim Gift Aid on my donation and any donations I make in the future or have made in the past 4 years*'

Note: I have not been told of any other links where we have this text that would need updated, so am assuming these are the only two instances.  Any others would need updated also.

Also, can we please have a note of the date and time this change goes live (is needed so we can backdate a task that will happen in the future)

**Comment by Heleen-cr** [comment]
@ajgowans 
What would you like to make of the text when it's a monthly donation?
It currently is: `Yes, I would like Comic Relief to claim Gift Aid on my monthly donations`
We could say: `Yes, I would like Comic Relief to claim Gift Aid on my monthly donations and donations I have made in the past 4 years`
Though one could make a donation separate from the recurring donations. So we could keep the text the same as what it is for a single donation perhaps..
What do you think?

**Comment by ajgowans** [comment]
@Heleen-cr - good point, have added in a note about future donations so that explicitly covers us for if they were to make a one off donation in the future outside of their monthly giving.  

"Yes, I would like Comic Relief to claim Gift Aid on my monthly donations, as well as any future donations and donations I have made in the past 4 years."

**Comment by Heleen-cr** [comment]
`giftaid` is live on production since 11:19:16
