### ISSUE TITLE
Add Sport Relief Logo to the Gift Aid Page

### ISSUE THREAD

**Issue by ajgowans** [comicrelief/giftaid-react#218]
Can we add the Sport Relief logo to sit next to the CR logo on the gift aid page and update gift aid page

https://giftaid.sportrelief.com/

https://giftaid.comicrelief.com/update

**Comment by ajgowans** [comment]
@AndyEPhipps @LouiaR - can we please also add this to the update gift aid page?  https://giftaid.comicrelief.com/update

**Comment by AndyEPhipps** [comment]
I think the header is common to all pages already
