### ISSUE TITLE
Update design with new logo (Giftaid)

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/giftaid-react#229]
This will work much like how it currently does, changing the logo etc. based on the URL.

We'll just need a new to check against `giftaid.bignightin.tv`

**Comment by Ruby-HB** [comment]
GiftAid page design - with logo header
![image](https://user-images.githubusercontent.com/59445264/78549006-95ae1f80-77f9-11ea-8cd2-e0a0f104dc65.png)
