### ISSUE TITLE
White space is displayed below footer on BNI thankyou page 

### ISSUE THREAD

**Issue by KrupaPammi** [comicrelief/giftaid-react#248]
Only on tablets portrait view

![Screen Shot 2020-04-16 at 12 21 46](https://user-images.githubusercontent.com/16117926/79454758-ade52200-7fe3-11ea-9797-1c522919f36b.png)

**Comment by CarolineRennie** [comment]
I do slightly hate it but can also live with it....

**Comment by CarolineRennie** [comment]
based on 98% of giftaid traffic is mobile - this is tolerable

**Comment by KrupaPammi** [comment]
cool, will close it then.
