### ISSUE TITLE
Design tidy-up for header

### ISSUE THREAD

**Issue by LaBustaffa** [comicrelief/giftaid-react#26]
Subtask of #1

**Comment by LaBustaffa** [comment]
Design tidied-up! 

It should all be in line with expectations. The information on gift Aid has been aligned to the message we have on online donate, while the form reflects the latest decisions for form design. 

The format of some links will be discussed tomorrow, but what is there now is the current option for other links on the site. (On hover the links turns red).

[Gift Aid form - Desktop.pdf](https://github.com/comicrelief/giftaid-react/files/2067939/Gift.Aid.form.-.Desktop.pdf)

**Comment by LaBustaffa** [comment]
If possible, could the copy in the phone field read 'In the format' rather than 'use the format'?

**Comment by Heleen-cr** [comment]
That is very much possible :P

**Comment by LaBustaffa** [comment]
😆

**Comment by LaBustaffa** [comment]
Design updated.

**Comment by LaBustaffa** [comment]
There is now also a prototype that displays behaviour of the error message (triggered by not clicking on the checkbox but entering the address)

https://eh4pcu.axshare.com/ga_landing.html

**Comment by deniselashlley** [comment]
@pradip3271 ready for testing: https://deploy-preview-38--giftaid-react.netlify.com/

design here:
https://deploy-preview-38--giftaid-react.netlify.com/

**Comment by LaBustaffa** [comment]
Updated desktop design:
![image](https://user-images.githubusercontent.com/33353053/42218082-59dd9b46-7ebf-11e8-895e-35babca9fd22.png)

Updated smartphone design (the only thing that changed is the bold on the title):
![image](https://user-images.githubusercontent.com/33353053/42218117-7194bac6-7ebf-11e8-91f8-c890e3e0a7d3.png)

**Comment by pradip3271** [comment]
Passed QA, ready for release.

**Comment by LaBustaffa** [comment]
Design check: ok :)
