### ISSUE TITLE
Giftaid component

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#3]
subtask of #1 

![38424802-1580881e-39aa-11e8-8052-4d54d7a2ae48](https://user-images.githubusercontent.com/21171954/38874215-7d117558-424f-11e8-8925-1d3ec9200d53.png)

**Comment by Heleen-cr** [comment]
@CarolineRennie Currently the link "find out more about giftaid" goes to the RND FAQs. I suppose we're keeping this campaign agnostic now and link to https://www.comicrelief.com/frequently-asked-questions#gift-aid ?

**Comment by CarolineRennie** [comment]
Yes please

**Comment by Heleen-cr** [comment]
### Test notes: 
- go to https://deploy-preview-17--giftaid-react.netlify.com/
- underneath the header there should be a promo-header now with the giftaid title in it.
- the find out more about giftaid link should link to the FAQs on the comicrelief website.
