### ISSUE TITLE
Integrate improved Storybook-based MPs

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/giftaid-react#307]
To address issues raised in https://github.com/comicrelief/giftaid-react/pull/298#issuecomment-838615425

**Comment by AndyEPhipps** [comment]
Hi @KrupaPammi, here's the URL to test the updates: https://deploy-preview-308--giftaid-react.netlify.app/ (I found the test URL that _won't_ actually change if need commits are added)

Fixes:
- switching between Yes and No for any one option no longer clears the associated field(s), only when the option is unselected, and another
- Yup validation rules are added to both to the Email field and the Telephone field; please let me know if you do see anything unexpected in what is valid/invalid, but it _should_ be fine now

**Comment by KrupaPammi** [comment]
Thanks @AndyEPhipps will test

**Comment by KrupaPammi** [comment]
@AndyEPhipps Email field is working as expected now. Noticed that phone field is not accepting landline numbers now. Is there a change? Thought we agreed to allow both mobile and landline numbers for phone field unless if I missed something.

**Comment by KrupaPammi** [comment]
The space issue (0712 3456 789) I mentioned in dev forum this morning is fixed. Thanks for the fixes.

**Comment by AndyEPhipps** [comment]
> @AndyEPhipps Email field is working as expected now. Noticed that phone field is not accepting landline numbers now. Is there a change? Thought we agreed to allow both mobile and landline numbers for phone field unless if I missed something.

Hi @KrupaPammi, can you give me examples of you're trying, as I can see it working fine for both?
![Screen Shot 2021-05-14 at 14 44 25](https://user-images.githubusercontent.com/4737220/118279581-3540e580-b4c3-11eb-83ef-19624c33d1b4.png)
![Screen Shot 2021-05-14 at 14 45 45](https://user-images.githubusercontent.com/4737220/118279580-34a84f00-b4c3-11eb-9a30-bab2ee444d5c.png)
![Screen Shot 2021-05-14 at 14 46 28](https://user-images.githubusercontent.com/4737220/118279575-340fb880-b4c3-11eb-9adc-9d53ea9f705a.png)

**Comment by AndyEPhipps** [comment]
@KrupaPammi you can test the above update [here](https://deploy-preview-464--comicrelief-storybook.netlify.app/?knob-id=radioButtons4&knob-name=radiobuttons4&knob-label=Radio%20Buttons%3A%20not%20required%2C%20preselected&knob-Min%20Length=3&knob-Endpoint=https%3A%2F%2Flookups-staging.sls.comicrelief.com%2Fschools%2Flookup%3Fquery%3D&selectedKind=Marketing%20Consent&selectedStory=MarketingConsent&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by KrupaPammi** [comment]
@Andy ***@***.***> it’s showing error for London landline numbers that start with ‘0208’

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndyEPhipps** [comment]
Aha yeah, I can see that issue on the GA build; it looks like that update in SB fixed it though.

It should be fixed on the test GA env now too:

![Uploading Screen Shot 2021-05-14 at 15.37.47.png…]()

**Comment by KrupaPammi** [comment]
great, thanks

**Comment by KrupaPammi** [comment]
works now @AndyEPhipps, just noticed that when I edit (remove and add) a number in between a telephone or mobile number, I see the cursor moves to the end of the number not staying in the place where i removed the number.

**Comment by AndyEPhipps** [comment]
Hm.. I had to make some changes to the Inputfield component in order to add in this new validation.. I'll see if I can address it

**Comment by KrupaPammi** [comment]
From the last update I see that form isn't getting submitted for the first time with all valid inputs. Not sure if it's my internet. Had to click the submit button several times and wait or refresh and then start again. Could you submit and see if it's working fine please?

**Comment by AndyEPhipps** [comment]
> From the last update I see that form isn't getting submitted for the first time with all valid inputs. Not sure if it's my internet. Had to click the submit button several times and wait or refresh and then start again. Could you submit and see if it's working fine please?

It's submitting fine for me; when ignoring MPs, using them without erroring, or forcing errors to happen, attempting to submit and then fixing them.  If it happens again, could you check the Network tab for me to see if there's any reason why the BE might be stopping the submission?

**Comment by KrupaPammi** [comment]
Seems to be working now filling and not filling MPs. I tried on incognito earlier not sure why it didn't work. Thanks for checking.

**Comment by AndyEPhipps** [comment]
> Seems to be working now filling and not filling MPs. I tried on incognito earlier not sure why it didn't work. Thanks for checking.

Sometimes the submission seems to take ages!

**Comment by KrupaPammi** [comment]
Would you be able to look into it if possible?

**Comment by AndyEPhipps** [comment]
It's very sporadic and only ever seems to happen on a non-prod env, but I'll have a look if it happens again

**Comment by KrupaPammi** [comment]
Cool, thanks

**Comment by AndyEPhipps** [comment]
Hi @KrupaPammi, I've **_FINALLY_** been able to find a solution for the input cursor/caret issue, QA-able on the test env: https://deploy-preview-308--giftaid-react.netlify.app/

**Comment by KrupaPammi** [comment]
Hi @AndyEPhipps Thanks for fixing the above issue, works as expected now. Just found another issue with 'phone' field allowing alphabets. 

Here are few issues:

1. When I enter any number of alphabets at the front of the number, no error message displayed, form is submitted but going to sorry page. Expected: should not allow any alphabets in number field, only numeric value

![Screen Shot 2021-05-19 at 11 57 31](https://user-images.githubusercontent.com/16117926/118802060-9a1c8700-b899-11eb-9d19-eff7712f2e90.png)

![Screen Shot 2021-05-19 at 11 53 51](https://user-images.githubusercontent.com/16117926/118802087-a274c200-b899-11eb-92c1-e51290e0078f.png)

2. Error message is displayed when I enter alphabets in between the first 3 digits of mobile/telephone number which is fine but if I enter any 2 alphabets after the first 3 digits but before the last number, then no error message displayed. Expected: should not allow any alphabets in number field, only numeric value

![Screen Shot 2021-05-19 at 11 52 57](https://user-images.githubusercontent.com/16117926/118802401-fbdcf100-b899-11eb-8df8-2f8123ff7267.png)

![Screen Shot 2021-05-19 at 12 02 52](https://user-images.githubusercontent.com/16117926/118802600-36df2480-b89a-11eb-86d3-921f4f1b971f.png)

3. When i enter more than 3 alphabets at the end of the mobile/telephone value, then I see a error message, same when I enter between the number too, but expected is, display error message when any alphabet is entered whether front of the number, end of the number or in between.

![Screen Shot 2021-05-19 at 11 54 01](https://user-images.githubusercontent.com/16117926/118802853-8cb3cc80-b89a-11eb-9f31-6a9be5daf921.png)

**Comment by AndyEPhipps** [comment]
Hmm, this plugin seems to be less and less useful. I'll see if it's any more customisable

**Comment by AndyEPhipps** [comment]
Okeydokey, have managed to add an additional regex check to check it'll only match numbers; with or without spaces, and also a `+` at the start for international numbers:

![Screen Shot 2021-05-19 at 13 52 48](https://user-images.githubusercontent.com/4737220/118815885-9133b180-b8a9-11eb-893a-f61268d58f14.png)
![Screen Shot 2021-05-19 at 13 52 27](https://user-images.githubusercontent.com/4737220/118815888-91cc4800-b8a9-11eb-860c-d298e3d09fd0.png)
![Screen Shot 2021-05-19 at 13 52 19](https://user-images.githubusercontent.com/4737220/118815889-9264de80-b8a9-11eb-90c9-69c93e079416.png)
![Screen Shot 2021-05-19 at 13 52 08](https://user-images.githubusercontent.com/4737220/118815892-9264de80-b8a9-11eb-9ca9-3e8e06b98d70.png)

**Comment by AndyEPhipps** [comment]
I'm not really sure about this point though?

> Error message is displayed when I enter alphabets in between the first 3 digits of mobile/telephone number **which is fine**
Surely we can't allow any characters that aren't alphabetic, spaces or the +, as previously mentioned?

**Comment by KrupaPammi** [comment]
It works fine with your fix now, previously it was allowing up to 2alphabets in between the number like this '0208hy5694142' without showing an error message, when I add 3 alphabets eg '0208569abc4242' it was then showing the error. Sorry if that was not clear.

> I'm not really sure about this point though?
> 
> > Error message is displayed when I enter alphabets in between the first 3 digits of mobile/telephone number _**which is fine**_
> 
> Surely we can't allow any characters that aren't alphabetic, spaces or the + at the start, as previously mentioned? That's what I've implemented, as I'm not sure of any phone format that would need them?

**Comment by AndyEPhipps** [comment]
Oh wait, I totally misread it, sorry! That terrible night's sleep is really catching up with me, I think it's break time!

**Comment by KrupaPammi** [comment]
No worries :)

**Comment by KrupaPammi** [comment]
Tested it @AndyEPhipps, works expected now. Have updated the tests with all the latest changes here https://github.com/comicrelief/giftaid-react/pull/309 we can merge the PRs once reviewed.

**Comment by AndyEPhipps** [comment]
Great, thanks @KrupaPammi! Will just sort out the Storybook release now and update here
