### ISSUE TITLE
End-to-end data testing

### ISSUE THREAD

**Issue by pradip3271** [comicrelief/giftaid-react#45]

**Comment by pradip3271** [comment]
Test data: https://docs.google.com/spreadsheets/d/1eqGpxD3XXMF6CgFJzn3I4FtijXyhuYlS9owUrWEirsU/

**Comment by pradip3271** [comment]
Issues
1. TransType and TransSource on db getting wrong values.
2. From staging env. data not consuming to DB.

**Comment by pradip3271** [comment]
Passed QA

**Comment by Heleen-cr** [comment]
@pradip3271 can we do a final test on staging / production?

**Comment by pradip3271** [comment]
Tested on production data consuming as expected - Passed QA
