### ISSUE TITLE
Postcode lookup component

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#5]
subtask of #1 

![38424802-1580881e-39aa-11e8-8052-4d54d7a2ae48](https://user-images.githubusercontent.com/21171954/38874712-a44cb7bc-4250-11e8-931e-118c0c76757c.png)

**Comment by Heleen-cr** [comment]
postcode lookup endpoint: https://lookups.sls.comicrelief.com/postcode/lookup?query=se17tp

**Comment by CarolineRennie** [comment]
@adamclark-dev to share the React donate build of this

**Comment by adamclark-dev** [comment]
Here you go @CarolineRennie ,

https://github.com/comicrelief/react-donation/blob/master/src/component/Pages/Address/AddressLookup/AddressLookup.js
