### ISSUE TITLE
Scroll to and focus erroring form field

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#52]
When pressing submit and there is an erroring form field: scroll to and focus on first erroring field.

**Comment by Heleen-cr** [comment]
### test notes
- go to https://deploy-preview-55--giftaid-react.netlify.com/
- test accros browsers
- test if values are coming through properly
- Note: some browsers don't scroll or focus on the erroring field on submit, but scroll the form into view instead (e.g. IE).

**Comment by pradip3271** [comment]
Passed QA, ready for release.
