### ISSUE TITLE
Update header with new CR logo

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#54]

**Comment by CarolineRennie** [comment]
@AndyEPhipps to provide SVG for header logo

**Comment by AndyEPhipps** [comment]
SVG lives here in this house: https://github.com/comicrelief/comicrelief/pull/525

**Comment by Heleen-cr** [comment]
We've decided to remove the campaign logos, because the new red nose day logo doesn't really look good together with the new cr logo and the sportrelief logo.
