### ISSUE TITLE
Frontend for /update page

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/giftaid-react#74]
https://github.com/comicrelief/serverless-giftaid/issues/18

Design is ready!
Interactive prototype: https://50cr8l.axshare.com (where you see it can be clicked there is an interaction, otherwise refer to the current gift aid journey interaction)

Visual design is attached here and found in: CR product development > Gift Aid > Gift Aid - user journey.sketch or CR product development > Gift Aid > Edit declaration

![image](https://user-images.githubusercontent.com/33353053/43960216-401dd33a-9ca9-11e8-963c-9e1149897a3f.png)
![image](https://user-images.githubusercontent.com/33353053/43960218-41f3a5c2-9ca9-11e8-8d31-7c5e7cc8c2b0.png)
![image](https://user-images.githubusercontent.com/33353053/43960220-44158320-9ca9-11e8-81b0-c841cfb4b10f.png)
![image](https://user-images.githubusercontent.com/33353053/43960223-4603717e-9ca9-11e8-877f-e8fae3f8bfc5.png)

**Comment by AndyEPhipps** [comment]
@LaBustaffa @CarolineRennie : would the existing checkbox solution for the declaration work here? i.e.:

![screen shot 2018-08-21 at 16 58 23](https://user-images.githubusercontent.com/4737220/44413556-8bc3a400-a563-11e8-9320-69a642f543b5.png)

rather than what's in the design:
![screen shot 2018-08-21 at 16 59 37](https://user-images.githubusercontent.com/4737220/44413607-aa299f80-a563-11e8-8595-6cb5583c7b18.png)

Trying to reuse as much existing stuff as possible here

**Comment by LaBustaffa** [comment]
We introduced a different design to make it easier and clearer to say 'no', thinking it's a bit ambiguous otherwise. If it's a long piece of work to create the new element I might do a quick test to see which design works best in this context.

**Comment by AndyEPhipps** [comment]
Okay, cool; I'll look at getting the radio buttons into the storybook tomorrow so they'll be easily reusable

**Comment by AndyEPhipps** [comment]
@CarolineRennie @LaBustaffa : I'm guessing we need an Update-specific sorry page too? Current copy for the normal GA journey is:

```

Sorry!
We’re really sorry, but with people across the UK rushing to Gift Aid their text donation, our site is a bit overwhelmed and has had to have a lie down.

Please try again in 5
Gift Aid costs you nothing, and we use it to pay for our operational costs.

If it’s been longer than 15 minutes please make a note of the website address: giftaid.rednoseday.com and please try again in a few hours.

Thanks for your support.
```

**Comment by k-pammi** [comment]
@LaBustaffa do we have a design for the radio buttons when they are selected?

**Comment by LaBustaffa** [comment]
We can follow what we do elsewhere for radio buttons: https://pattern-lab.services.comicrelief.com/rnd/section-10.html#kssref-10-90

**Comment by k-pammi** [comment]
cool, thanks @LaBustaffa
