### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#8]
subtask of #1 

![38424802-1580881e-39aa-11e8-8052-4d54d7a2ae48](https://user-images.githubusercontent.com/21171954/38874797-de960ff4-4250-11e8-8fdd-d044d1ae7e2f.png)

**Comment by Heleen-cr** [comment]
### Test notes:
- go to https://deploy-preview-19--giftaid-react.netlify.com/
- the footer should be present and have the comic relief theming and links.

**Comment by pradip3271** [comment]
Passed QA, ready for release.
