### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/giftaid-react#9]
Might need to be split up into thank you component and some routing? 

subtask of #1 

![38425496-eb86b1e4-39ab-11e8-8617-c1af5340ccbf](https://user-images.githubusercontent.com/21171954/38880528-dc8d3d10-425d-11e8-8781-08ae05e1cd74.png)

**Comment by CarolineRennie** [comment]
Update - we would like to use this thank you page as a way to capture marketing preferences after the form has been submitted

**Comment by LaBustaffa** [comment]
First version - without the marketing preferences - is ready. 
https://comicrelief.box.com/s/nex90ryjcj0ivmbcap5v2nymqd4nphlm

![image](https://user-images.githubusercontent.com/33353053/41667481-02b1aff2-74a5-11e8-919a-3fcda6d01688.png)

**Comment by deniselashlley** [comment]
@LaBustaffa can I have the assets of the two boys for the promo header

**Comment by LaBustaffa** [comment]
Link to box folder: https://comicrelief.box.com/s/5sk3ncqldxi7fdgcrjm8r8lpuyr06mrb

Let me know what size the mobile version should be. I'm worried that the page will be slow on desktop/tablet as well, is there a way to check that?

**Comment by deniselashlley** [comment]
@pradip3271 and @LaBustaffa Ready for QA: https://deploy-preview-35--giftaid-react.netlify.com/success
- the username is not being pull through until i get the rest of the form submission working it just placeholder for now.

**Comment by LaBustaffa** [comment]
Just two small things: 
- The only thing I can see is that the CR style of the links should be applied (big red underline)
- the question mark is missing from the end of the title

thanks

**Comment by pradip3271** [comment]
Passed QA, ready for release.
